#!/bin/sh

CFGFILE=$1
if [ $CFGFILE = '-d' ] ; then
	CFGFILE='package.cfg';
	DEBUG='-d';
elif [ -z $CFGFILE ] ; then
	CFGFILE='package.cfg';
else
	DEBUG=$2;
fi

perl $DEBUG templates/autosub -c $CFGFILE -c templates/system.cfg -d . -x \~ templates/templates
